name: check

on:
  push:
    branches:
      - '*'
      - !master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ['12']
    name: test and deploy
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn test
